package mediendatenbank.gui;

import mediendatenbank.BibDatabase;

public class BibStatisticsDlg extends javax.swing.JDialog {

	public BibStatisticsDlg(java.awt.Frame parent) {
		super(parent, true);
		initComponents();
		updateCount();
		setLocationRelativeTo(parent);
	}

	public final void updateCount() {
		Integer count = BibDatabase.get().countEntries();
		if (count != null) {
			countNumLbl.setText(count.toString());
		}
		Integer countAudio = BibDatabase.get().countEntries(BibDatabase.Type.AUDIO);
		if (countAudio != null) {
			countNumAudioLbl.setText(countAudio.toString());
		}
		Integer countVideo = BibDatabase.get().countEntries(BibDatabase.Type.VIDEO);
		if (countVideo != null) {
			countNumVideoLbl.setText(countVideo.toString());
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countLbl = new javax.swing.JLabel();
        dbHeaderLbl = new javax.swing.JLabel();
        countNumLbl = new javax.swing.JLabel();
        countAudioLbl = new javax.swing.JLabel();
        countNumAudioLbl = new javax.swing.JLabel();
        countNumVideoLbl = new javax.swing.JLabel();
        countVideoLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistiken");
        setResizable(false);

        countLbl.setFont(BibFont.getRegular());
        countLbl.setText("Summe:");

        dbHeaderLbl.setFont(BibFont.getBold());
        dbHeaderLbl.setText("Datenbank-Einträge");

        countNumLbl.setFont(BibFont.getRegular());
        countNumLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countNumLbl.setText("Unbekannt");

        countAudioLbl.setFont(BibFont.getRegular());
        countAudioLbl.setText("Audio:");

        countNumAudioLbl.setFont(BibFont.getRegular());
        countNumAudioLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countNumAudioLbl.setText("Unbekannt");

        countNumVideoLbl.setFont(BibFont.getRegular());
        countNumVideoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countNumVideoLbl.setText("Unbekannt");

        countVideoLbl.setFont(BibFont.getRegular());
        countVideoLbl.setText("Video:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(countLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(countVideoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(countAudioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countNumAudioLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(countNumVideoLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(countNumLbl, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countAudioLbl)
                    .addComponent(countNumAudioLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countVideoLbl)
                    .addComponent(countNumVideoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countNumLbl)
                    .addComponent(countLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countAudioLbl;
    private javax.swing.JLabel countLbl;
    private javax.swing.JLabel countNumAudioLbl;
    private javax.swing.JLabel countNumLbl;
    private javax.swing.JLabel countNumVideoLbl;
    private javax.swing.JLabel countVideoLbl;
    private javax.swing.JLabel dbHeaderLbl;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
